package.json, src/components/common/DropDownCommunity.vue, src/components/common/Headers.vue, src/components/common/Sidebar.vue, src/layouts/LayoutMain.vue, src/pages/Home.vue, src/store/sidebar.js, tailwind.config.js, yarn.lock
- close #17 
- 상단 툴 바 생성
- 사이드 바 mui icons 적용
- 랜딩 페이지 반응형 퍼블리싱 완료
=> [merge / 17-bug-modify_sidebar_icons] ✨ Feat: 사이드바 mui icons 적용, 랜딩 페이지 반응형 디자인 적용

tailwind.config.js
- close #21 
- Tailwind에 사용자 정의 색상 추가
이런 식으로 사용하시면 됩니다 ♪(´▽｀)
=> [merge / 21-add-tailwind-custom-colors] 📝 docs: Tailwind에 사용자 정의 색상 추가

src/pages/Join.vue
- close #37 
- 회원가입 페이지 퍼블리싱 
( •̀ ω •́ )y
=> [merge / 37-join-page-ui] ✨ feat: 회원가입 페이지 퍼블리싱

src/components/common/DropDownCommunity.vue, src/components/common/Sidebar.vue, tailwind.config.js
- close #35 
- 모든 모바일 디바이스에서 사이드바 영역 컨텐츠 올바르게 노출 되도록 반응형 UI 적용
=> [merge / 35-sidebar-flexible-ui] 💄 style: 사이드바 모바일 반응형 적용

.github/workflows/deploy-netlify.yml, package.json, src/config/supabase.js, yarn.lock
- close #46
- 슈퍼베이스를 연동해서 테스트 해보았는데 잘 작동합니다.
- pull 받으시고 yarn 으로 supabase 깔아주시고, .env에 제가 보내드리는 거 추가해주시면 사용가능합니다.
=> [merge / 46-supabase-initial-settings] ✨ feat: supabase 초기 세팅 완료

index.html, src/components/common/Calender.vue, src/components/common/DropDownDiary.vue, src/components/common/GlassBox.vue, src/pages/Diary.vue, src/router/index.js
- close #31 
-  캘린더, 날짜 선택버튼, glassbox컴포넌트 추가
=> :sparkles: feat:일기장 캘린더 컴포넌트&유리박스 컴포넌트 추가

src/main.js
- close #59 
- `main.js`에서 vuetify가 이중 선언되어 `yarn dev` 가 작동하지 않는 오류 해결 
♪(´▽｀)
=> [merge / 59-vuetify-double-declared] 🐛 fix: vuetify 이중 선언 오류 해결

src/pages/Home.vue, src/pages/Login.vue
- close #62 
- login 로직에 data.user.id 매개변수 추가
=> [merge /62-problems-loading-email-login-data] 🐛 fix: login 매개변수 수정

src/components/common/Calender.vue, src/components/common/DropDownDiary.vue, src/pages/Diary.vue, src/pages/DiaryDetails.vue, src/router/index.js
- close #52 
- 드롭다운 날짜 선택 시 캘린더 불러오기 코드 추가
=> [merge / 52-diary-calender-ui] :art: add: 드롭박스 날짜 불러오기 코드 추가

src/App.vue, src/components/common/Modal.vue, src/store/modalStore.js
- close #66 
- 커스텀 모달창 구현
- isOneBtn으로 버튼 1개, 2개 나눌 수 있습니다
=> [merge / 66-create-modal-components] ✨ feat: 커스텀 모달창 구현

src/components/common/Calender.vue, src/pages/DiaryDetails.vue, src/pages/diary-pages/Diary.vue, src/router/index.js
- close #68 
- 폴더구조 변경 관련 오류 수정
=> [merge / 68-diary-calender-responsive-ui] :bug: fix: 폴더구조변경 오류해결

src/components/common/Input.vue, src/pages/Join.vue, src/pages/Login.vue, src/pages/community-pages/PostDetails.vue, src/router/index.js
- close #71 
- 커스텀 Input passwordToggle 추가
- 로그인 및 회원가입 검증 오류 구현 => 로그인하기, 회원가입 버튼 누를 시에만 모달창 띄우기
- 라우터 index.js에서 로그인 중일 때 beforeEach를 통해서 login, join페이지로 접근 불가능하게 막아 놓음
- Oauth에서 로그인하면 토큰 값과 리프레쉬 토큰을 새로고침하기 전까지 보여줬었는데 index.js 에서 afterEach를 통해서 URL 해쉬 제거함.
- Input 컴포넌트 수정하고 Input 쓰인 곳이 정상작동하는지 확인 하는 도중에 PostDetails.vue 댓글인풋에 class-name으로 되어있어서 class로 수정했습니다.
- ༼ つ ◕_◕ ༽つ ฅʕ•̫͡•ʔฅ ༼ つ ◕_◕ ༽つ
=> [merge / 71-implementation-of-membership-verification-errors] ✨ feat: 로그인, 회원가입 검증, 로그인 중일때 회원가입,로그인 페이지 접근 불가능 , input 컴포넌트 수정

package.json, src/pages/Record.vue, vite.config.js, yarn.lock
- close #69 
- 음성인식으로 꿈 기록하기 
- AI로 꿈 분석하기
- 꿈 분석 결과 복사하기
- AI로 꿈 시각화하기
- 기분에 맞는 유튜브 asmr 추천하기
https://github.com/user-attachments/assets/f96aa6e8-4fa8-4e81-ba63-a86c5d02d362
o(*°▽°*)o
=> [merge / 69-record-dream] ✨ feat: 꿈기록 작성 페이지 구현

src/pages/my-pages/ProfileEdit.vue
- close #75 
- 이메일 로그인 시 프로필 변경, 자기소개 변경, 비밀번호 변경이 가능합니다
- Oauth 로그인시 프로필 변경, 자기소개 변경만 가능합니다.
- 비밀번호 변경/확인 이 똑같아야 저장 버튼이 활성화 됩니다.
- 프로필 사진만 바꿀 수도 있고 자기소개만 바꿀 수도 있고 비밀번호만 바꿀 수도 있습니다. => 바꾸고 싶은것만 바꾸고 저장하면 됩니다.
https://github.com/user-attachments/assets/1dabcca0-2443-4ecd-9509-e5fb0a9b62e7
- ༼ つ ◕_◕ ༽つ༼ つ ◕_◕ ༽つ༼ つ ◕_◕ ༽つ༼ つ ◕_◕ ༽つ༼ つ ◕_◕ ༽つ
=> [merge / 75-implementing-modifying-my-page-profile] ✨ feat: 마이페이지 프로필 편집 구현

src/components/common/DatePicker.vue, src/components/common/DropDownFace.vue, src/components/common/DropDownWeather.vue, src/pages/diary-pages/DiaryWrite.vue, src/router/index.js
- close #67 
- 라우팅
- DiaryWrite 페이지 퍼블리싱
- 반응형 미완
- 버튼 미완
=> [merge / 67-diary-write-page-ui] ✨ feat: 일기장 작성 페이지 퍼블리싱 (미완)

src/api/api-community/imgsApi.js, src/components/community/DragDropImg.vue, src/pages/community-pages/CommunityBoard.vue, src/pages/community-pages/CreatePost.vue, src/pages/community-pages/PostDetails.vue, src/pages/community-pages/UpdatePost.vue, vite.config.js
- close #80 
- 커뮤니티 게시물 상세페이지에서 미리보기로 마운트된 이미지를 조작할 때 미리보기 이미지가 비정상적으로 동작하는 현상 수정함.
=> [merge / 80-community-image-modify-error] 🐛 Fix: 게시물 상세페이지 이미지 수정시 마운트된 미리보기 오류 해결

src/components/common/Modal.vue, src/pages/Join.vue, src/pages/Login.vue
- close #87 
- 모달창 폰트 수정
- 사용가능한 이메일, 아이디 띄우기 추가
- oauth 로그인 모달창 삭제
- ヾ(⌐■_■)ノ♪(⌐■_■) (▀̿Ĺ̯▀̿ ̿) ༼ つ ◕_◕ ༽つ ฅʕ•̫͡•ʔฅ
=> [merge / 87-modal-component-modification]🐛 Fix: 모달창 폰트, 로그인, 회원가입 로직 수정

src/pages/Record.vue, src/pages/diary-pages/DiaryWrite.vue, src/store/diaryStore.js
- close #94 
- 꿈 기록 페이지와 일기장 작성 페이지의 데이터를 연결
- Pinia로 데이터 상태 관리
https://github.com/user-attachments/assets/9de2dfbb-8b1e-452c-a603-d18a640505ba
=> [merge / 94-record-diary-data-connect] ✨ feat: 꿈 기록 페이지와 일기장 작성 페이지의 데이터 연결, Pinia로 상태 관리 

src/api/api-diary/api.js, src/components/common/Calender.vue
- close #77 
- 달력 전체보기 페이지와 상세페이지의 데이터 연동
=> [merge /  77-calender-data-connect] :sparkles: feat: 달력-상세 데이터 연동

src/components/common/Button.vue, src/pages/Follow.vue, src/pages/Join.vue, src/pages/my-pages/Profile.vue, src/router/index.js, src/store/followStore.js
- close #90 
- 유저 프로필에서 마이페이지로 이동할 수 있으며 => 팔로잉, 팔로워 목록을 확인하고 팔로우 할 수 있습니다.
- 회원가입시 닉네임 검증 추가했습니다.
- 라우터 경로 수정했습니다.
- 버튼 사이즈 임시로 xl 로 추가해 두었습니다.
=> [merge / 90-user-page-connect] ✨ Feat: 유저 마이페이지, 팔로우 페이지 구현, 라우터 수정

src/api/api-like/api.js, src/components/common/LikesCounter.vue, src/pages/community-pages/Comment.vue, src/pages/community-pages/CommentList.vue, src/pages/community-pages/PostDetails.vue
- close #106 
- 로그인 하지 않았을 경우 게시물 상세페이지 내용을 열람할 수 없었던 에러 해결
=> [merge / 106-cannot-view-postitems]🐛 Fix: 로그인 하지 않았을 경우 게시물 상세페이지 내용을 열람할 수 없었던 에러 해결

src/components/common/Headers.vue, src/components/common/LikesCounter.vue, src/pages/Home.vue, src/pages/community-pages/Comment.vue, src/pages/community-pages/CommunityBoard.vue, src/pages/community-pages/PostDetails.vue
- close #111 
- 로그인 하지 않고 일부 기능 접근 시도시 로그인 안내 모달 팝업 기능 구현 완료
=> [merge / 111-community-modal]✨ Feat: 로그인 하지 않고 일부 기능 접근 시도시 로그인 안내 모달 팝업 기능 구현 완료

src/api/api-follow/api.js, src/pages/community-pages/CommentList.vue, src/pages/community-pages/PostDetails.vue
- close #121 
- 게시물 상세페이지 유저 프로필 이미지 또는 닉네임 영역 클릭시 해당 유저 프로필 페이지로 이동하는 기능 구현
- 커뮤니티 게시글 상세페이지 팔로우 버튼 활성화 완료
=> [merge / 121-community-follow-btn] ✨ Feat: 커뮤니티 게시글 상세페이지 팔로우 버튼 활성화 완료

src/components/community/SkeletonFollow.vue, src/pages/Follow.vue
- close #117 
- 팔로우 페이지 스켈레톤 ui 구현
https://github.com/user-attachments/assets/fad3f86d-6646-42f9-924e-7382f71aa7ec
- ฅʕ•̫͡•ʔฅฅʕ•̫͡•ʔฅฅʕ•̫͡•ʔฅฅʕ•̫͡•ʔฅฅʕ•̫͡•ʔฅฅʕ•̫͡•ʔฅฅʕ•̫͡•ʔฅฅʕ•̫͡•ʔฅ
=> [merge / 117-following-page-skeleton]✨ Feat: 팔로우 페이지 스켈레톤 구현

index.html, src/api/api-record/api.js, src/pages/Record.vue
- close #113 
- 일기 작성 페이지 이동 버튼 제어하여 하루에 여러 번 일기 작성이 가능하던 오류 해결
- 전체 페이지에서 모든 텍스트 선택이 불가능하도록
- 반응형 UI 수정 
(❁´◡`❁)
=> [merge / 113-fix-restrict-record-diary-button] 🐛 fix: 하루에 꿈 기록 페이지에서 일기 작성 페이지로 여러 번 이동 가능한 오류 해결

src/pages/community-pages/CommunityBoard.vue
- close #125 
- 커뮤니티 게시물 목록 검색기능 구현 완료
=> [merge / 125-community-search-bar] ✨ Feat: 커뮤니티 게시물 목록 검색기능 구현 완료

src/pages/Home.vue, src/pages/Record.vue
- close #129 
- 홈 화면에 추천 asmr 영상 임베드 
- 추천 asmr 새로 불러오기 버튼 추가 
- 추천 asmr skeleton 구현 
- vuetify의 skeleton 컴포넌트를 사용했더니 커스텀에 제한이 있어, 이후에 vuetify 사용하지 않고 직접 만들겠습니다.
- 유튜브 동영상이 임베드 되지 않는 오류는 새 api를 써서 해결했습니다 ➡️ env 파일 공유하겠습니다.
=> [merge / 129-main-asmr-recommendation] ✨ feat: 홈 화면에 추천 asmr 영상 임베드

src/pages/my-pages/Profile.vue
- close #135 
- 다른 사용자 프로필 화면에서 내 프로필 화면으로 이동 오류 수정
- ヾ(⌐■_■)ノ♪
=> [merge / 135-problems-switching-profile-screens]🐛 fix: 다른 사용자 프로필 화면에서 내 프로필 화면으로 이동 오류 수정

package.json, src/pages/community-pages/CommunityBoard.vue, yarn.lock
- close #133 
- 커뮤니티 게시물 목록 pagination 기능 구현 완료
=> [merge / 133-community-postlist-pagination] ✨ Feat: 커뮤니티 게시물 목록 pagination 기능 구현 완료

src/pages/Follow.vue, src/pages/my-pages/Profile.vue, src/pages/my-pages/ProfileEdit.vue
- close #139 
- 마이페이지 팔로잉 오류 수정했습니다.
- ฅʕ•̫͡•ʔฅ
=> [merge / 139-my-page-follow-error]🐛 fix: 마이페이지 팔로잉 오류 수정

src/api/api-diary/api.js, src/components/common/Calender.vue, src/pages/diary-pages/DiaryDetails.vue, src/pages/diary-pages/DiaryWrite.vue, src/pages/diary-pages/UpdateDiary.vue, src/router/index.js
- close #130 
- 일기 수정 및 삭제 기능 추가
- 일기 작성시 textarea 테두리 삭제
- 달력에 day가 같으면 사진이 중복으로 나오는 문제 해결
=> [merge / 130-diary-modal] :sparkles: feat: 일기수정/삭제기능 추가

src/components/common/Headers.vue, src/components/common/LikesCounter.vue, src/pages/community-pages/Comment.vue, src/pages/community-pages/PostDetails.vue, src/store/followStore.js
- close #132 
- 알림 생성시 헤더의 알림 아이콘에 레드닷(hc-pink) 나타남
- 알림 생성 기능 구현 (like, comment, follow)
- 만약 헤더의 알림 아이콘에 레드닷이 있는 채로 로그아웃을 하면 레드닷이 그대로 남아있어서 수정 필요할 것 같아요
=> [merge / 132-notification-create] ✨ Feat: 알림 생성 기능 구현

index.html, src/pages/community-pages/PostDetails.vue
- close #152 
- 카카오 공유하기 -> 지금은 로컬호스트임니다
- ~o( =∩ω∩= )m✍️(◔◡◔)ฅʕ•̫͡•ʔฅヾ(⌐■_■)ノ♪(⌐■_■)┗|｀O′|┛༼ つ ◕_◕ ༽つ
=> [merge / 152-implementing-kakao-sharing] ✨ Feat: 카카오 공유하기 초안 완성

src/pages/Follow.vue
- close #150 
- 팔로잉&모든유저 목록 페이지 반응형 퍼블리싱
=> [merge / 150-follow-ui-rwd] ✨ Feat: 팔로잉&모든유저 목록 페이지 반응형 퍼블리싱

package.json, src/components/common/Headers.vue, src/components/common/Sidebar.vue, src/store/sidebar.js, yarn.lock
- close #154 
- 외부 영역 클릭 이벤트 개선
=> [merge / 154-sidebar-click-event] 🐛 Fix: sidebar 외부 영역 클릭 이벤트 개선

.github/workflows/deploy-netlify.yml
=> [merge / 162-deployment-test] 🐛 Fix: 배포를 위한 yml 파일 수정

src/components/common/Calender.vue, src/pages/diary-pages/Diary.vue, src/pages/diary-pages/DiaryDetails.vue
- close #148 
- 달력 반응형 디자인 적용, 일기상세 모달창 디자인 통일
=> [merge/148-diary-calender-responsive-ui] :sparkles: feat:달력 반응형적용, 모달 디자인 통일

src/pages/Notification.vue
- close #159 
- follow 알림 목록에서 라우팅 수정
=> [merge / 159-notification-follow-link]✨ Feat: 알림 follow 라우팅 수정

src/pages/diary-pages/Diary.vue, src/pages/diary-pages/DiaryDetails.vue, src/pages/diary-pages/DiaryWrite.vue
- close #178 
- 일기 캘린더 반응형 수정 및 일기 작성, 수정, 상세 반응형 추가
=> [merge/178-diary-responsive-ui] :bug: fix: 반응형 수정 및 추가

src/components/common/Input.vue, src/pages/Join.vue, src/pages/Login.vue, src/pages/NotFound.vue
- close #175 
- 404 페이지 헤더 아이콘 통일
- 로그인, 회원가입 페이지 헤더 아이콘 통일
- 로그인, 회원가입 페이지 반응형 퍼블리싱
=> [merge / 175-login-join-ui-rwd] ✨Feat: 로그인, 회원가입 페이지 반응형 퍼블리싱

src/pages/my-pages/ProfileEdit.vue
- close #185 
- 카카오톡 로그인 시에도 프로필 편집 페이지가 잘 나타남
=> [merge / 185-profile-edit-null-bug] 🐛 Fix: null 설정 추가

src/components/common/CoverflowSwiper.vue, src/pages/Home.vue, src/pages/community-pages/Comment.vue, src/pages/community-pages/CommentList.vue, src/pages/community-pages/CommunityBoard.vue, src/pages/community-pages/PostDetails.vue
- close #186 
- 커뮤니티 반응형 UI 일부 수정
=> [merge / 186-home-community-se-ui] 🐛 Fix: 홈 / 커뮤니티 반응형 UI 일부 수정

src/components/common/Sidebar.vue, src/pages/community-pages/PostDetails.vue, src/store/followStore.js
- close #191 
- postDetails 타입에러 수정
=> [merge / 191-community-refactor-type-error] 🐛 Fix: postDetails 타입에러 수정

src/components/common/CoverflowSwiper.vue, src/components/common/MeatballsMenu.vue, src/pages/Home.vue, src/pages/community-pages/CommentList.vue, src/pages/community-pages/CommunityBoard.vue, src/pages/community-pages/CreatePost.vue, src/pages/community-pages/PostDetails.vue, src/pages/community-pages/UpdatePost.vue
- close #201 
- 홈 화면 꿈 기록버튼 모바일 반응형 UI 개선
- 커뮤니티 게시물 영역 이벤트 발생시 모달 노출
- 커뮤니티 게시물 상세페이지 목록으로 이동 버튼 생성
- 일부 css 개선
=> [merge / 201-home-mobile-ui] 🐛 Fix: 홈 화면 및 커뮤니티 화면 일부 기능 개선

src/components/common/Calender.vue, src/pages/diary-pages/Diary.vue, src/pages/diary-pages/DiaryDetails.vue, src/pages/diary-pages/DiaryWrite.vue
- close #194 
- 캘린더, 작성페이지 다크모드 수정, 호버 크기변경
=> [merge / 194-diary-ui] :bug: fix: 일기작성, 상세, 캘린더 ui수정

src/components/common/Button.vue, src/components/common/CoverflowSwiper.vue, src/components/common/DropDownNewPost.vue, src/components/common/Headers.vue, src/components/common/LikesCounter.vue, src/components/common/ScrollTopButton.vue, src/components/common/Sidebar.vue, src/pages/Home.vue, src/pages/community-pages/CommunityBoard.vue, src/pages/community-pages/CreatePost.vue, src/pages/community-pages/PostDetails.vue, src/pages/community-pages/UpdatePost.vue, src/pages/diary-pages/DiaryDetails.vue, src/pages/diary-pages/DiaryWrite.vue
- close #207 
- 홈, 커뮤니티, 다이어리 다크 모드 일부 수정
=> [merge / 207-modify-community-UI] ✨ Feat: 다크모드 일부 수정

README.md
=> [merge / 213-create-readme] ✨ Feat: 리드미 초안 작성

src/pages/Join.vue, src/pages/Record.vue, src/pages/community-pages/CreatePost.vue, src/pages/my-pages/ProfileEdit.vue
- close #215 
-  alert로 되어있는 것들 modal 로 바꾸기
=> [merge / 215-replace-alert-with-modal] ✨ Feat: 알림창 모달창으로 바꾸기

src/pages/community-pages/CommunityBoard.vue, src/pages/community-pages/UpdatePost.vue
- close #212 
- 포스트 생성시 버튼 ui 수정
=> [merge /  212-fix-create-post-darkmode-button] 🐛 Fix: 포스트 생성시 버튼 ui 수정

src/pages/Record.vue
- close #221 
- AI 생성 이미지 로더 구현 
♪(´▽｀)
=> [merge / 221-ai-image-loader] ✨ feat: AI 생성 이미지 로더 구현

src/pages/community-pages/PostDetails.vue
- close #223 
- 게시물 상세 페이지의 댓글 작성자 프로필 사진 비율 1:1로 자르게 수정
=> [merge / 223-postdetails-authorimg-ui-edit] ✨ Feat: 게시물 상세 페이지 댓글 작성자 프로필 사진 비율 수정

src/pages/my-pages/Profile.vue
- close #226 
- 프로필 페이지 다크모드에서 프로필 편집 버튼 색상 반응형 수정
- 게시물 그리드 모든 화면 크기에서 반응형 적용
- 프로필 편집 버튼 크기 반응형 수정
=> [merge / 226-profile-button-dark-ui-edit] 🐛Fix: 프로필 페이지 반응형 추가 수정

src/api/api-community/api.js, src/api/api-community/imgsApi.js, src/api/api-diary/api.js, src/api/api-like/api.js, src/components/common/DropDown.vue, src/components/common/DropDownDiary.vue, src/pages/Record.vue, src/pages/community-pages/CommunityBoard.vue, src/pages/community-pages/CreatePost.vue, src/pages/community-pages/UpdatePost.vue, src/pages/diary-pages/Diary.vue, src/pages/diary-pages/DiaryDetails.vue, src/store/authStore.js, src/store/followStore.js, src/store/notificationsStore.js, src/store/sidebar.js
=> [merge / 230-delete-console] ♻refactor: console.log 삭제

src/components/common/Calender.vue, src/pages/diary-pages/Diary.vue
- close #229 
- 라이트모드 날짜불러오기, 미로그인 경로 수정
=> [merge / 229-calender-ui] :bug :fix: 라이트모드 날짜불러오기, 미로그인 경로 수정

src/pages/Notification.vue
- close #232 
- 알림 목록의 양옆 여백 추가
- 알림 목록의 텍스트 반응형 수정
- 로고 크기 반응형 수정
- 알림 목록 height 반응형 수정
=> [merge / 232-notification-ui-rwd-edit]🐛 Fix: 알림 페이지 반응형 수정

README.md
=> [merge ] 📝 docs: README 수정 (트러블슈팅)

src/pages/diary-pages/DiaryWrite.vue
- close #236 
- 일기작성 미로그인 경로 추가
=> [merge / 236-diary-write-ui] :bug :fix: 일기작성 미로그인 경로 추가

src/pages/Home.vue
=> [merge /  239-enable-youtube-api] ✨ Feat: 유튜브 API 활성화

src/pages/Join.vue
- close #242 
- 회원가입 페이지 이메일/닉네임 부분 반응형 UI 수정
=> [merge / 242-join-button-ui-rwd-edit] 🐛 Bug: 회원가입 페이지 반응형 버튼 수정

src/components/common/LikesCounter.vue, src/components/common/Sidebar.vue, src/pages/Home.vue, src/pages/Record.vue, src/pages/community-pages/Comment.vue, src/pages/community-pages/PostDetails.vue, src/pages/diary-pages/Diary.vue
=> [merge /  244-modify-login-modal] 🐛  Fix: 로그인 안내 모달 전수 수정
